#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace reference::protocol_constants {

inline constexpr std::uint64_t protocol_schema_version = 1ULL;
inline constexpr std::string_view protocol_spec_sha256{"e9c7e3b986e1ed6a56030b8689a027486141291d682af2f6d0d58f05df4f257b"};
inline constexpr std::string_view byte_order{"little"};
inline constexpr std::string_view bit_order{"lsb_first"};
inline constexpr std::uint64_t sequence_bits = 32ULL;
inline constexpr std::uint64_t sequence_initial = 0ULL;
inline constexpr std::uint64_t sequence_modulus = 4294967296ULL;
inline constexpr std::uint64_t frame_version = 0ULL;
inline constexpr std::uint64_t frame_max_payload_bytes = 1024ULL;
inline constexpr std::uint64_t frame_header_size = 6ULL;
inline constexpr std::uint64_t crc32c_polynomial = 517762881ULL;
inline constexpr std::uint64_t crc32c_reflected_polynomial = 2197175160ULL;
inline constexpr std::uint64_t crc32c_initial = 4294967295ULL;
inline constexpr std::uint64_t crc32c_xor_out = 4294967295ULL;
inline constexpr std::uint64_t token_record_version = 1ULL;
inline constexpr std::uint64_t token_record_base_size = 40ULL;
inline constexpr std::uint64_t extension_tlv_header_size = 2ULL;
inline constexpr std::uint64_t extension_tlv_max_value_bytes = 255ULL;
inline constexpr std::uint64_t protection_request_version = 1ULL;
inline constexpr std::uint64_t protection_request_size = 16ULL;
inline constexpr std::uint64_t channel_state_version = 1ULL;
inline constexpr std::uint64_t channel_state_size = 4ULL;
inline constexpr std::uint64_t result_status_size = 8ULL;
inline constexpr std::uint64_t error_response_size = 8ULL;
inline constexpr std::uint64_t stream_byte_data_bits = 8ULL;
inline constexpr std::uint64_t stream_bit_data_bits = 1ULL;
inline constexpr std::uint64_t message_type_ping = 1ULL;
inline constexpr std::uint64_t message_type_pong = 2ULL;
inline constexpr std::uint64_t message_type_token_request = 16ULL;
inline constexpr std::uint64_t message_type_token_result = 17ULL;
inline constexpr std::uint64_t message_type_error_response = 127ULL;
inline constexpr std::uint64_t token_flag_generated_time_valid = 1ULL;
inline constexpr std::uint64_t token_flag_deadline_valid = 2ULL;
inline constexpr std::uint64_t protection_mode_none = 0ULL;
inline constexpr std::uint64_t protection_mode_repetition = 1ULL;
inline constexpr std::uint64_t protection_mode_hamming_7_4 = 2ULL;
inline constexpr std::uint64_t channel_flag_quality_valid = 1ULL;
inline constexpr std::uint64_t result_flag_parity_error = 1ULL;
inline constexpr std::uint64_t result_flag_fec_corrected = 2ULL;
inline constexpr std::uint64_t result_flag_crc_error = 4ULL;
inline constexpr std::uint64_t result_flag_malformed_frame = 8ULL;
inline constexpr std::uint64_t result_flag_malformed_request = 16ULL;
inline constexpr std::uint64_t result_flag_unsupported_version = 32ULL;
inline constexpr std::uint64_t result_flag_unsupported_protection = 64ULL;
inline constexpr std::uint64_t result_flag_sequence_gap = 128ULL;
inline constexpr std::uint64_t result_flag_uart_framing_error = 256ULL;
inline constexpr std::uint64_t result_flag_internal_overflow = 512ULL;
inline constexpr std::uint64_t frame_sof_offset = 0ULL;
inline constexpr std::uint64_t frame_sof_size = 2ULL;
inline constexpr std::uint64_t frame_version_offset = 2ULL;
inline constexpr std::uint64_t frame_version_size = 1ULL;
inline constexpr std::uint64_t frame_message_type_offset = 3ULL;
inline constexpr std::uint64_t frame_message_type_size = 1ULL;
inline constexpr std::uint64_t frame_flags_offset = 4ULL;
inline constexpr std::uint64_t frame_flags_size = 2ULL;
inline constexpr std::uint64_t frame_payload_length_offset = 6ULL;
inline constexpr std::uint64_t frame_payload_length_size = 2ULL;
inline constexpr std::uint64_t token_record_record_version_offset = 0ULL;
inline constexpr std::uint64_t token_record_record_version_size = 1ULL;
inline constexpr std::uint64_t token_record_flags_offset = 1ULL;
inline constexpr std::uint64_t token_record_flags_size = 1ULL;
inline constexpr std::uint64_t token_record_base_length_offset = 2ULL;
inline constexpr std::uint64_t token_record_base_length_size = 2ULL;
inline constexpr std::uint64_t token_record_stream_id_offset = 4ULL;
inline constexpr std::uint64_t token_record_stream_id_size = 4ULL;
inline constexpr std::uint64_t token_record_sequence_offset = 8ULL;
inline constexpr std::uint64_t token_record_sequence_size = 4ULL;
inline constexpr std::uint64_t token_record_token_id_offset = 12ULL;
inline constexpr std::uint64_t token_record_token_id_size = 4ULL;
inline constexpr std::uint64_t token_record_importance_offset = 16ULL;
inline constexpr std::uint64_t token_record_importance_size = 1ULL;
inline constexpr std::uint64_t token_record_reserved_0_offset = 17ULL;
inline constexpr std::uint64_t token_record_reserved_0_size = 3ULL;
inline constexpr std::uint64_t token_record_generated_time_us_offset = 20ULL;
inline constexpr std::uint64_t token_record_generated_time_us_size = 8ULL;
inline constexpr std::uint64_t token_record_deadline_us_offset = 28ULL;
inline constexpr std::uint64_t token_record_deadline_us_size = 8ULL;
inline constexpr std::uint64_t token_record_extension_length_offset = 36ULL;
inline constexpr std::uint64_t token_record_extension_length_size = 2ULL;
inline constexpr std::uint64_t token_record_reserved_1_offset = 38ULL;
inline constexpr std::uint64_t token_record_reserved_1_size = 2ULL;
inline constexpr std::uint64_t protection_request_request_version_offset = 0ULL;
inline constexpr std::uint64_t protection_request_request_version_size = 1ULL;
inline constexpr std::uint64_t protection_request_mode_offset = 1ULL;
inline constexpr std::uint64_t protection_request_mode_size = 1ULL;
inline constexpr std::uint64_t protection_request_flags_offset = 2ULL;
inline constexpr std::uint64_t protection_request_flags_size = 2ULL;
inline constexpr std::uint64_t protection_request_block_length_bits_offset = 4ULL;
inline constexpr std::uint64_t protection_request_block_length_bits_size = 2ULL;
inline constexpr std::uint64_t protection_request_repetition_count_offset = 6ULL;
inline constexpr std::uint64_t protection_request_repetition_count_size = 1ULL;
inline constexpr std::uint64_t protection_request_reserved_0_offset = 7ULL;
inline constexpr std::uint64_t protection_request_reserved_0_size = 1ULL;
inline constexpr std::uint64_t protection_request_code_rate_num_offset = 8ULL;
inline constexpr std::uint64_t protection_request_code_rate_num_size = 2ULL;
inline constexpr std::uint64_t protection_request_code_rate_den_offset = 10ULL;
inline constexpr std::uint64_t protection_request_code_rate_den_size = 2ULL;
inline constexpr std::uint64_t protection_request_reserved_1_offset = 12ULL;
inline constexpr std::uint64_t protection_request_reserved_1_size = 4ULL;
inline constexpr std::uint64_t channel_state_state_version_offset = 0ULL;
inline constexpr std::uint64_t channel_state_state_version_size = 1ULL;
inline constexpr std::uint64_t channel_state_flags_offset = 1ULL;
inline constexpr std::uint64_t channel_state_flags_size = 1ULL;
inline constexpr std::uint64_t channel_state_channel_quality_offset = 2ULL;
inline constexpr std::uint64_t channel_state_channel_quality_size = 2ULL;
inline constexpr std::uint64_t result_status_flags_offset = 0ULL;
inline constexpr std::uint64_t result_status_flags_size = 4ULL;
inline constexpr std::uint64_t result_status_corrected_count_offset = 4ULL;
inline constexpr std::uint64_t result_status_corrected_count_size = 2ULL;
inline constexpr std::uint64_t result_status_detected_error_count_offset = 6ULL;
inline constexpr std::uint64_t result_status_detected_error_count_size = 2ULL;
inline constexpr std::uint64_t error_response_flags_offset = 0ULL;
inline constexpr std::uint64_t error_response_flags_size = 4ULL;
inline constexpr std::uint64_t error_response_request_message_type_offset = 4ULL;
inline constexpr std::uint64_t error_response_request_message_type_size = 1ULL;
inline constexpr std::uint64_t error_response_reserved_offset = 5ULL;
inline constexpr std::uint64_t error_response_reserved_size = 3ULL;
inline constexpr std::array<std::uint8_t, 2> frame_sof{0xA5U, 0x5AU};

}
