[project]
name = "llm-token-fec-fpga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yosuke", email = "yosuke.t.7.sea@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "llama-cpp-python>=0.3.34",
]

[project.scripts]
llm-token-fec-fpga = "llm_token_fec_fpga:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
