[project]
name = "llm-token-fec-fpga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yosuke", email = "yosuke.t.7.sea@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.27.0",
    "llama-cpp-python>=0.3.34",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "polars>=1.43.2",
    "pyserial>=3.5",
    "pyyaml>=6.0.3",
    "scipy>=1.18.0",
    "tqdm>=4.70.0",
]

[project.scripts]
llm-token-fec-fpga = "llm_token_fec_fpga:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
